import type { Metadata } from "next";
import {DM_Sans} from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
const font  = DM_Sans({ subsets: ["latin"] });
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >  
    <html lang="en">
      <body className={font.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          
      </body>
    </html></ClerkProvider>
  );
}
